CXX            = g++
VISP_CFLAGS    = `$(VISP_INSTALL_PREFIX)/bin/visp-config --cflags`
VISP_LDFLAGS   = `$(VISP_INSTALL_PREFIX)/bin/visp-config --libs`

SOURCES=$(shell find . -name "sample*.cpp")
TARGETS=$(SOURCES:%.cpp=%)

all: $(TARGETS)

%: %.cpp
	$(CXX) $(VISP_CFLAGS) -o $@ $< $(VISP_LDFLAGS)

clean:
	rm -f *~ $(TARGETS)

